run:
  concurrency: 8
  deadline: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - .go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 30
  govet:
    check-shadowing: false
  goconst:
    min-len: 3
    min-occurrences: 4

linters:
  disable-all: true
  enable: # NOTE: please keep this list alphabetically sorted
    - bodyclose
    - deadcode
    - dogsled
    - errcheck
    - goconst
    - gocyclo
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  fast: false



