---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "event-consumer-external"
spec:
  ports:
    -
      name: "vdu"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
      nodePort: 0
---
apiVersion: "v1"
kind: "Endpoints"
metadata:
  name: "event-consumer-external"
subsets:
  - addresses:
      - ip: "10.22.32.248"  #change this to your laptop ip address
    ports:
      - port: 3306
        name: "vdu"
